### ISSUE TITLE
about code

### ISSUE THREAD

**Issue by cenchaojun** [aimagelab/PMA-Net#1]
Thank you for your great work!👍
Looking forward to the release of your code

**Comment by luchen-zhang** [comment]
I'm interested in your research.Looking forward to the release of your code.

**Comment by sarasarto** [comment]
Thanks for your interest in our work. We apologize for the delay, but we are on track to release it within the next few weeks.

**Comment by hzf-hhh** [comment]
> Thanks for your interest in our work. We apologize for the delay, but we are on track to release it within the next few weeks.

Sorry to bother you, but I would like to ask when there is an open source plan for the code

**Comment by sarasarto** [comment]
Dear all, 
thank you again for your interest in our work. The source code has been finally released. Sorry for the delay! 
Let us know if you encounter any problems.
