### ISSUE TITLE
About open-source code

### ISSUE THREAD

**Issue by zzzyzh** [aimagelab/PMA-Net#2]
Thank you for your excellent work!

In the last issue you mentioned that you were hopeful of releasing the code in a few weeks, would like to ask if you have any plans for open source code these days?

I'd really like to try your work!

**Comment by moon4869** [comment]
Me too, I am looking forward to trying your excellent work as soon as possible!!

**Comment by detectRecog** [comment]
How soon? It has been already half a year.

**Comment by sarasarto** [comment]
Dear all, 
thank you for your interest in our work. The source code has been finally released. Sorry for the delay! 
Let us know if you encounter any problems.
